env:
  browser: true
  es2021: true
  node: true
  jest: true
extends: airbnb-base
overrides: []
parserOptions:
  ecmaVersion: latest
rules: 
  max-classes-per-file: 0
  linebreak-style:
    - error
    - windows
  prefer-destructuring:
  - error
  - object: true
    array: false
  import/extensions:
  - error
  - js: ignorePackages
globals:
  actions: writable